name: Local
variables:
  - name: baseUrl
    value: http://localhost:3000
  - name: reportId
    value: 995f75c8-c87b-4061-95b0-424210aaf138
  - name: projectId
    value: a3934e18-95a0-4d90-b6e4-2c88cc9c02c5
  - name: page
    value: "2"
  - name: limit
    value: "1"
